// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihzdpypseamrkynffdsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloemRweXBzZWFtcmt5bmZmZHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTczNzMsImV4cCI6MjA2NTU5MzM3M30.rTsvUf3Dd21DZS1qomDiM1FzjKLrczRNUsv3MdixdyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);